# Generated by Django 4.2.4 on 2023-10-25 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Добавьте юзернейм', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username не соответствует регулярному выражению ^[\\w.@+-]+\\Z', regex='^[\\w.@+-]+\\Z')], verbose_name='Юзернейм'),
        ),
    ]
